all: backButton.png backButtonPressed.png levelLocked.png levelUnlocked.png levelUnlockedPressed.png mainPlayButton.png mainPlayButtonPressed.png orcaButton.png pauseButton.png pauseButtonPressed.png replayLevelButton.png replayLevelButtonPressed.png scoreBoardButton.png scoreBoardButtonPressed.png helpButton.png helpButtonPressed.png playButton.png playButtonPressed.png selectButton.png selectButtonPressed.png nextButton.png nextButtonPressed.png starGold.png starWhite.png starGoldBig.png starWhiteBig.png nextLevel.png nextLevelPressed.png checkButton.png checkButtonPressed.png forwardButton.png forwardButtonPressed.png tryAgainButton.png tryAgainButtonPressed.png showAnswerButton.png showAnswerButtonPressed.png achievementButton.png achievementButtonPressed.png achievementsGreyButton.png

mainPlayButton.png: ../webgraphics/mainPlayButton.png
	convert ../webgraphics/mainPlayButton.png -resize 400x mainPlayButton.png

mainPlayButtonPressed.png: ../webgraphics/mainPlayButtonPressed.png
	convert ../webgraphics/mainPlayButtonPressed.png -resize 400x mainPlayButtonPressed.png

backButton.png: ../webgraphics/backButton.png
	convert ../webgraphics/backButton.png -resize 90x89 backButton.png

backButtonPressed.png: ../webgraphics/backButtonPressed.png
	convert ../webgraphics/backButtonPressed.png -resize 90x89 backButtonPressed.png

levelLocked.png: ../webgraphics/levelLocked.png
	convert ../webgraphics/levelLocked.png -resize 102x128 levelLocked.png

levelLockedPressed.png: ../webgraphics/levelLockedPressed.png
	convert ../webgraphics/levelLockedPressed.png -resize 102x128 levelLockedPressed.png

levelUnlocked.png: ../webgraphics/levelUnlocked.png
	convert ../webgraphics/levelUnlocked.png -resize 102x128 levelUnlocked.png

levelUnlockedPressed.png: ../webgraphics/levelUnlockedPressed.png
	convert ../webgraphics/levelUnlockedPressed.png -resize 102x128 levelUnlockedPressed.png

orcaButton.png: ../webgraphics/orcaButton.png
	convert ../webgraphics/orcaButton.png -resize 200x200 orcaButton.png

orcaButtonPressed.png: ../webgraphics/orcaButtonPressed.png
	convert ../webgraphics/orcaButtonPressed.png -resize 200x200 orcaButtonPressed.png

pauseButton.png: ../webgraphics/pauseButton.png
	convert ../webgraphics/pauseButton.png -resize 92x90 pauseButton.png

pauseButtonPressed.png: ../webgraphics/pauseButtonPressed.png
	convert ../webgraphics/pauseButtonPressed.png -resize 92x90 pauseButtonPressed.png

replayLevelButton.png: ../webgraphics/replayLevel.png
	convert ../webgraphics/replayLevel.png -resize 90x replayLevelButton.png

replayLevelButtonPressed.png: ../webgraphics/replayLevelPressed.png
	convert ../webgraphics/replayLevelPressed.png -resize 90x replayLevelButtonPressed.png

scoreBoardButton.png: ../webgraphics/scoreBoard.png
	convert ../webgraphics/scoreBoard.png -resize 90x scoreBoardButton.png

scoreBoardButtonPressed.png: ../webgraphics/scoreBoardPressed.png
	convert ../webgraphics/scoreBoardPressed.png -resize 90x scoreBoardButtonPressed.png

helpButton.png: ../webgraphics/helpButton.png
	convert ../webgraphics/helpButton.png -resize 85x85 helpButton.png

helpButtonPressed.png: ../webgraphics/helpButtonPressed.png
	convert ../webgraphics/helpButtonPressed.png -resize 85x85 helpButtonPressed.png

playButton.png: ../webgraphics/playButton.png
	convert ../webgraphics/playButton.png -resize 85x83 playButton.png

playButtonPressed.png: ../webgraphics/playButtonPressed.png
	convert ../webgraphics/playButtonPressed.png -resize 85x83 playButtonPressed.png

forwardButton.png: ../webgraphics/forwardButton.png
	convert ../webgraphics/forwardButton.png -resize 85x83 forwardButton.png

forwardButtonPressed.png: ../webgraphics/forwardButtonPressed.png
	convert ../webgraphics/forwardButtonPressed.png -resize 85x83 forwardButtonPressed.png

selectButton.png: ../webgraphics/selectButton.png
	convert ../webgraphics/selectButton.png -resize 200x selectButton.png

selectButtonPressed.png: ../webgraphics/selectButtonPressed.png
	convert ../webgraphics/selectButtonPressed.png -resize 200x selectButtonPressed.png

nextButton.png: ../webgraphics/nextButton.png
	convert ../webgraphics/nextButton.png -resize 200x nextButton.png

nextButtonPressed.png: ../webgraphics/nextButtonPressed.png
	convert ../webgraphics/nextButtonPressed.png -resize 200x nextButtonPressed.png

starGold.png: ../webgraphics/starGold.png
	convert ../webgraphics/starGold.png -resize 21x starGold.png

starGoldPressed.png: ../webgraphics/starGoldPressed.png
	convert ../webgraphics/starGoldPressed.png -resize 21x starGoldPressed.png

starWhite.png: ../webgraphics/starWhite.png
	convert ../webgraphics/starWhite.png -resize 21x starWhite.png

starWhitePressed.png: ../webgraphics/starWhitePressed.png
	convert ../webgraphics/starWhitePressed.png -resize 21x starWhitePressed.png

starGoldBig.png: ../webgraphics/starGold.png
	convert ../webgraphics/starGold.png -resize 62x starGoldBig.png

starGoldBigPressed.png: ../webgraphics/starGoldPressed.png
	convert ../webgraphics/starGoldPressed.png -resize 62x starGoldBigPressed.png

starWhiteBig.png: ../webgraphics/starWhite.png
	convert ../webgraphics/starWhite.png -resize 62x starWhiteBig.png

starWhiteBigPressed.png: ../webgraphics/starWhitePressed.png
	convert ../webgraphics/starWhitePressed.png -resize 62x starWhiteBigPressed.png

nextLevel.png: ../webgraphics/nextLevel.png
	convert ../webgraphics/nextLevel.png -resize 90x nextLevel.png

nextLevelPressed.png: ../webgraphics/nextLevelPressed.png
	convert ../webgraphics/nextLevelPressed.png -resize 90x nextLevelPressed.png

checkButton.png: ../webgraphics/checkButton.png
	convert ../webgraphics/checkButton.png -resize 90x checkButton.png

checkButtonPressed.png: ../webgraphics/checkButtonPressed.png
	convert ../webgraphics/checkButtonPressed.png -resize 90x checkButtonPressed.png

tryAgainButton.png: ../webgraphics/tryAgainButton.png
	convert ../webgraphics/tryAgainButton.png -resize 300x tryAgainButton.png

tryAgainButtonPressed.png: ../webgraphics/tryAgainButtonPressed.png
	convert ../webgraphics/tryAgainButtonPressed.png -resize 300x tryAgainButtonPressed.png

showAnswerButton.png: ../webgraphics/showAnswerButton.png
	convert ../webgraphics/showAnswerButton.png -resize 300x showAnswerButton.png

showAnswerButtonPressed.png: ../webgraphics/showAnswerButtonPressed.png
	convert ../webgraphics/showAnswerButtonPressed.png -resize 300x showAnswerButtonPressed.png

achievementButton.png: ../webgraphics/cupButton.png
	convert ../webgraphics/cupButton.png -resize 90x achievementButton.png

achievementButtonPressed.png: ../webgraphics/cupButtonPressed.png
	convert ../webgraphics/cupButtonPressed.png -resize 90x achievementButtonPressed.png

cupButton.png: ../webgraphics/scoreButton.png
	convert ../webgraphics/scoreButton.png -resize 90x cupButton.png

cupButtonPressed.png: ../webgraphics/scoreButtonPressed.png
	convert ../webgraphics/scoreButtonPressed.png -resize 90x cupButtonPressed.png

achievementsGreyButton.png: ../webgraphics/achievementsGreyButton.png
	convert ../webgraphics/achievementsGreyButton.png -resize 100x achievementsGreyButton.png

