all: mainScreen.jpg doneScreen.jpg playScreen.jpg guessMatchedScreen.jpg guessDidntMatchScreen.jpg currentReferenceUndefined.jpg helpScreen0.jpg 

mainScreen.jpg: ../../webgraphics/ornithopedia/mainScreen.png
	convert ../../webgraphics/ornithopedia/mainScreen.png -resize "1024x" mainScreen.jpg

doneScreen.jpg: ../../webgraphics/ornithopedia/doneScreen.png
	convert ../../webgraphics/ornithopedia/doneScreen.png -resize "1024x" doneScreen.jpg

playScreen.jpg: ../../webgraphics/ornithopedia/playScreen.png
	convert ../../webgraphics/ornithopedia/playScreen.png -resize "1024x" playScreen.jpg

guessMatchedScreen.jpg: ../../webgraphics/ornithopedia/guessMatchedScreen.png
	convert ../../webgraphics/ornithopedia/guessMatchedScreen.png -resize "1024x" guessMatchedScreen.jpg

guessDidntMatchScreen.jpg: ../../webgraphics/ornithopedia/guessDidntMatchScreen.png
	convert ../../webgraphics/ornithopedia/guessDidntMatchScreen.png -resize "1024x" guessDidntMatchScreen.jpg

currentReferenceUndefined.jpg: ../../webgraphics/ornithopedia/currentReferenceUndefined.png
	convert ../../webgraphics/ornithopedia/currentReferenceUndefined.png -resize "1024x" currentReferenceUndefined.jpg

helpScreen0.jpg: ../../webgraphics/ornithopedia/helpScreen0.png
	convert ../../webgraphics/ornithopedia/helpScreen0.png -resize "1024x" helpScreen0.jpg

